/**
 * @file      hardware.h (180.ARM_Peripherals/Project_Headers/hardware.h)
 *
 * This file is a convenient location for shared USBDM namespace information and
 * brings together header files for basic USBDM features
 *
 * @version  V4.12.1.80
 * @date     13 April 2016
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "pit.h"
#include "adc.h"
#include "cmp.h"
#include "ftm.h"


namespace USBDM {

/// Measurement ADC
using MeasurementADC                 = const Adc0;                                        

/// Measurement ADC
extern const Adc0                                  measurementADC;                 

/// ADC channel connected to high gain  amplifier
extern const Adc0::Channel<0>                      highGainAdcChannel;             // p7

extern const Adc0::Channel<6>                      ch1Identify;                    // p46

extern const Adc0::Channel<7>                      ch2Identify;                    // p47

/// ADC channel connected to low gain  amplifier
extern const Adc0::Channel<19>                     lowGainAdcChannel;              // p8

/// Internal temperature sensor T = (25 - (Tvolts-0.719)/.001715)
extern const Adc0::Channel<26>                     chipTemperatureAdcChannel;      // Internal

// No ADC1 declarations found
// No ADC2 declarations found
// No CMT declarations Found
// No CAN0 declarations Found
// No CAN1 declarations Found
// No CAN2 declarations Found

/// Mains zero-crossing comparator
using ZeroCrossingComparator         = const Cmp0;                                        

/// Mains zero-crossing comparator
extern const Cmp0                                  zeroCrossingComparator;         

/// AC zero Crossing Detector Comparator input
extern const Cmp0::Pin<1>                          zeroCrossingInput;              // p40


/// Over-current comparator
using OverCurrentComparator          = const Cmp1;                                        

/// Over-current comparator
extern const Cmp1                                  overCurrentComparator;          

/// Over-current Detector Comparator input
extern const Cmp1::Pin<5>                          overcurrent;                    // p13

// No CMP2 declarations Found
// No CMP3 declarations Found
// No CMT0 declarations Found
// No CMT1 declarations Found
// No CMT2 declarations Found
// No CRC declarations Found
// No CRC0 declarations Found

/// Spare pin for debugging
extern const GpioA<4>                              debug;                          // p21


/// Quadrature Encoder pins (Bit Field)
extern const GpioBField<1, 0, ActiveLow>           quadPhases;                     // p27-p28

/// Stand sensors (Bit Field)
extern const GpioBField<17, 16, ActiveLow>         setbacks;                       // p31-p32


/// Channel 1 Drive  (Bit Field)
extern const GpioCField<2, 1, ActiveLow>           ch1Drive;                       // p34-p35

/// Channel 1 Selected LED
extern const GpioC<0>                              ch1SelectedLed;                 // p33

/// Channel 2 Selected LED
extern const GpioC<6>                              ch2SelectedLed;                 // p39

/// Controls clamp at input of amplifier chain (output of mux)
extern const GpioC<5>                              clamp;                          // p38

/// Channel 2 Drive (Bit Field)
extern const GpioCField<4, 3, ActiveLow>           ch2Drive;                       // p36-p37


/// Quadrature encoder centre button
extern const GpioD<0, ActiveLow>                   quadButton;                     // p41

/// Channel 2 Button
extern const GpioD<1, ActiveLow>                   ch2Button;                      // p42

/// All buttons for polling (Bit Field)
extern const GpioDField<3, 0, ActiveLow>           buttons;                        // p41-p44

/// Channel 1 Button
extern const GpioD<2, ActiveLow>                   ch1Button;                      // p43

/// MenuButton
extern const GpioD<3, ActiveLow>                   menuButton;                     // p44

/// Bias enable on amplifier input
extern const GpioD<7>                              biasEnable;                     // p48

/// Mux&amplifier control (Bit Field)
extern const GpioDField<7, 4, 0b1>                 amplifierControl;               // p45-p48

/// Gain boost enable on amplifier
extern const GpioD<4, ActiveLow>                   highGainEnable;                 // p45

// No GPIOE declarations found
// No DAC0 declarations Found
// No DAC1 declarations Found
// No EWM declarations found
// No EWM declarations found
// No declarations Found

/// FTM used for channel drive (optional)
using DriveFtm                       = const Ftm0;                                        

/// FTM used for channel drive (optional)
extern const Ftm0                                  driveFtm;                       

// No FTM1 declarations found
// No FTM2 declarations found
// No FTM3 declarations found
// No I2C0 declarations found
// No I2C1 declarations found
// No I2C2 declarations found
// No I2C3 declarations found
// No I2C4 declarations found
// No I2S0 declarations found
// No I2S1 declarations found
// No I2S2 declarations found
// No LLWU declarations found
// No LPTMR0 declarations found
// No LPTMR1 declarations found
// No OSC0 declarations Found
// No OSC1 declarations Found

/// PIT Channel to use for switch polling
extern const Pit::Channel<0>                       pollingTimerChannel;            // Internal

/// PIT Channel to use for sample and control timing
extern const Pit::Channel<1>                       controlTimerChannel;            // Internal

// No PDB declarations found
// No PDB0 declarations found
// No PDB1 declarations found
// No PMC declarations found
// No RCM declarations found
// No RTC declarations found
// No SDHC0 declarations Found
// No SDRAMC declarations Found
// No SMC declarations found
// No SPI0 declarations found
// No SPI1 declarations found
// No SPI2 declarations found
// No SPI3 declarations found
// No TRNG0 declarations Found
// No TSI declarations found
// No TSI0 declarations found
// No UART0 declarations found
// No UART1 declarations found
// No UART2 declarations found
// No UART3 declarations found
// No UART4 declarations found
// No UART5 declarations found
// No USBDCD0 declarations found
// No VREF0 declarations found
// No WDOG declarations found
} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
